set TECHROOT "/prog/cadence/gpdk/g045/lan/flow/t1u1/reference_libs/GPDK045/gsclib045_all_v4.4"
set FLOWPATH "/home/mdaoudi/Documents/ic_project/PACoGen/synthesis/flow"
set DEFPATH "/home/mdaoudi/Documents/ic_project/PACoGen/synthesis/def"
set LEFPATH "/prog/cadence/gpdk/g045/lan/flow/t1u1/reference_libs/GPDK045/gsclib045_all_v4.4"
set CUSTOMLEFPATH ""

set CONSTRAINTPATH "/home/mdaoudi/Documents/ic_project/PACoGen/synthesis/constraints"
set SCRIPTPATH "/home/mdaoudi/Documents/ic_project/PACoGen/synthesis/flow/scripts"
set TECHPATH "/home/mdaoudi/Documents/ic_project/PACoGen/synthesis/flow/tech"
set RTLPATH "/home/mdaoudi/Documents/ic_project/PACoGen/synthesis/source"
set DBSPATH "/home/mdaoudi/Documents/ic_project/PACoGen/synthesis/dbs"
set REPORTPATH "/home/mdaoudi/Documents/ic_project/PACoGen/synthesis/reports"
set TOPMODULE "posit_mult"
set VERILOGFILES " /home/mdaoudi/Documents/ic_project/PACoGen/synthesis/source/posit_mult.v"
set VHDLFILES ""
set SDCFILE "/home/mdaoudi/Documents/ic_project/PACoGen/synthesis/constraints/timing_constraints.tcl"
set CPFFILE "/home/mdaoudi/Documents/ic_project/PACoGen/synthesis/constraints/power_domains.cpf"

