
//input ports
add mapped point clk clk -type PI PI
add mapped point reset reset -type PI PI
add mapped point reg_A[31] reg_A[31] -type PI PI
add mapped point reg_A[30] reg_A[30] -type PI PI
add mapped point reg_A[29] reg_A[29] -type PI PI
add mapped point reg_A[28] reg_A[28] -type PI PI
add mapped point reg_A[27] reg_A[27] -type PI PI
add mapped point reg_A[26] reg_A[26] -type PI PI
add mapped point reg_A[25] reg_A[25] -type PI PI
add mapped point reg_A[24] reg_A[24] -type PI PI
add mapped point reg_A[23] reg_A[23] -type PI PI
add mapped point reg_A[22] reg_A[22] -type PI PI
add mapped point reg_A[21] reg_A[21] -type PI PI
add mapped point reg_A[20] reg_A[20] -type PI PI
add mapped point reg_A[19] reg_A[19] -type PI PI
add mapped point reg_A[18] reg_A[18] -type PI PI
add mapped point reg_A[17] reg_A[17] -type PI PI
add mapped point reg_A[16] reg_A[16] -type PI PI
add mapped point reg_A[15] reg_A[15] -type PI PI
add mapped point reg_A[14] reg_A[14] -type PI PI
add mapped point reg_A[13] reg_A[13] -type PI PI
add mapped point reg_A[12] reg_A[12] -type PI PI
add mapped point reg_A[11] reg_A[11] -type PI PI
add mapped point reg_A[10] reg_A[10] -type PI PI
add mapped point reg_A[9] reg_A[9] -type PI PI
add mapped point reg_A[8] reg_A[8] -type PI PI
add mapped point reg_A[7] reg_A[7] -type PI PI
add mapped point reg_A[6] reg_A[6] -type PI PI
add mapped point reg_A[5] reg_A[5] -type PI PI
add mapped point reg_A[4] reg_A[4] -type PI PI
add mapped point reg_A[3] reg_A[3] -type PI PI
add mapped point reg_A[2] reg_A[2] -type PI PI
add mapped point reg_A[1] reg_A[1] -type PI PI
add mapped point reg_A[0] reg_A[0] -type PI PI
add mapped point reg_B[31] reg_B[31] -type PI PI
add mapped point reg_B[30] reg_B[30] -type PI PI
add mapped point reg_B[29] reg_B[29] -type PI PI
add mapped point reg_B[28] reg_B[28] -type PI PI
add mapped point reg_B[27] reg_B[27] -type PI PI
add mapped point reg_B[26] reg_B[26] -type PI PI
add mapped point reg_B[25] reg_B[25] -type PI PI
add mapped point reg_B[24] reg_B[24] -type PI PI
add mapped point reg_B[23] reg_B[23] -type PI PI
add mapped point reg_B[22] reg_B[22] -type PI PI
add mapped point reg_B[21] reg_B[21] -type PI PI
add mapped point reg_B[20] reg_B[20] -type PI PI
add mapped point reg_B[19] reg_B[19] -type PI PI
add mapped point reg_B[18] reg_B[18] -type PI PI
add mapped point reg_B[17] reg_B[17] -type PI PI
add mapped point reg_B[16] reg_B[16] -type PI PI
add mapped point reg_B[15] reg_B[15] -type PI PI
add mapped point reg_B[14] reg_B[14] -type PI PI
add mapped point reg_B[13] reg_B[13] -type PI PI
add mapped point reg_B[12] reg_B[12] -type PI PI
add mapped point reg_B[11] reg_B[11] -type PI PI
add mapped point reg_B[10] reg_B[10] -type PI PI
add mapped point reg_B[9] reg_B[9] -type PI PI
add mapped point reg_B[8] reg_B[8] -type PI PI
add mapped point reg_B[7] reg_B[7] -type PI PI
add mapped point reg_B[6] reg_B[6] -type PI PI
add mapped point reg_B[5] reg_B[5] -type PI PI
add mapped point reg_B[4] reg_B[4] -type PI PI
add mapped point reg_B[3] reg_B[3] -type PI PI
add mapped point reg_B[2] reg_B[2] -type PI PI
add mapped point reg_B[1] reg_B[1] -type PI PI
add mapped point reg_B[0] reg_B[0] -type PI PI

//output ports
add mapped point out[31] out[31] -type PO PO
add mapped point out[30] out[30] -type PO PO
add mapped point out[29] out[29] -type PO PO
add mapped point out[28] out[28] -type PO PO
add mapped point out[27] out[27] -type PO PO
add mapped point out[26] out[26] -type PO PO
add mapped point out[25] out[25] -type PO PO
add mapped point out[24] out[24] -type PO PO
add mapped point out[23] out[23] -type PO PO
add mapped point out[22] out[22] -type PO PO
add mapped point out[21] out[21] -type PO PO
add mapped point out[20] out[20] -type PO PO
add mapped point out[19] out[19] -type PO PO
add mapped point out[18] out[18] -type PO PO
add mapped point out[17] out[17] -type PO PO
add mapped point out[16] out[16] -type PO PO
add mapped point out[15] out[15] -type PO PO
add mapped point out[14] out[14] -type PO PO
add mapped point out[13] out[13] -type PO PO
add mapped point out[12] out[12] -type PO PO
add mapped point out[11] out[11] -type PO PO
add mapped point out[10] out[10] -type PO PO
add mapped point out[9] out[9] -type PO PO
add mapped point out[8] out[8] -type PO PO
add mapped point out[7] out[7] -type PO PO
add mapped point out[6] out[6] -type PO PO
add mapped point out[5] out[5] -type PO PO
add mapped point out[4] out[4] -type PO PO
add mapped point out[3] out[3] -type PO PO
add mapped point out[2] out[2] -type PO PO
add mapped point out[1] out[1] -type PO PO
add mapped point out[0] out[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point A[0]/q A_reg[0]/Q  -type DFF DFF
add mapped point A[1]/q A_reg[1]/Q  -type DFF DFF
add mapped point A[2]/q A_reg[2]/Q  -type DFF DFF
add mapped point A[3]/q A_reg[3]/Q  -type DFF DFF
add mapped point A[4]/q A_reg[4]/Q  -type DFF DFF
add mapped point A[5]/q A_reg[5]/Q  -type DFF DFF
add mapped point A[10]/q A_reg[10]/Q  -type DFF DFF
add mapped point A[12]/q A_reg[12]/Q  -type DFF DFF
add mapped point A[14]/q A_reg[14]/Q  -type DFF DFF
add mapped point A[31]/q A_reg[31]/Q  -type DFF DFF
add mapped point A[31]/q A_reg[31]/QN  -type DFF DFF
add mapped point B[2]/q B_reg[2]/Q  -type DFF DFF
add mapped point B[7]/q B_reg[7]/Q  -type DFF DFF
add mapped point B[8]/q B_reg[8]/Q  -type DFF DFF
add mapped point B[9]/q B_reg[9]/Q  -type DFF DFF
add mapped point B[10]/q B_reg[10]/Q  -type DFF DFF
add mapped point B[12]/q B_reg[12]/Q  -type DFF DFF
add mapped point B[13]/q B_reg[13]/Q  -type DFF DFF
add mapped point B[14]/q B_reg[14]/Q  -type DFF DFF
add mapped point B[16]/q B_reg[16]/Q  -type DFF DFF
add mapped point B[31]/q B_reg[31]/Q  -type DFF DFF
add mapped point B[31]/q B_reg[31]/QN  -type DFF DFF
add mapped point A[6]/q A_reg[6]/Q  -type DFF DFF
add mapped point A[6]/q A_reg[6]/QN  -type DFF DFF
add mapped point A[7]/q A_reg[7]/Q  -type DFF DFF
add mapped point A[7]/q A_reg[7]/QN  -type DFF DFF
add mapped point A[8]/q A_reg[8]/Q  -type DFF DFF
add mapped point A[8]/q A_reg[8]/QN  -type DFF DFF
add mapped point A[9]/q A_reg[9]/Q  -type DFF DFF
add mapped point A[9]/q A_reg[9]/QN  -type DFF DFF
add mapped point A[11]/q A_reg[11]/Q  -type DFF DFF
add mapped point A[11]/q A_reg[11]/QN  -type DFF DFF
add mapped point A[13]/q A_reg[13]/Q  -type DFF DFF
add mapped point A[13]/q A_reg[13]/QN  -type DFF DFF
add mapped point A[15]/q A_reg[15]/Q  -type DFF DFF
add mapped point A[15]/q A_reg[15]/QN  -type DFF DFF
add mapped point A[16]/q A_reg[16]/Q  -type DFF DFF
add mapped point A[16]/q A_reg[16]/QN  -type DFF DFF
add mapped point A[17]/q A_reg[17]/Q  -type DFF DFF
add mapped point A[17]/q A_reg[17]/QN  -type DFF DFF
add mapped point A[18]/q A_reg[18]/Q  -type DFF DFF
add mapped point A[18]/q A_reg[18]/QN  -type DFF DFF
add mapped point A[19]/q A_reg[19]/Q  -type DFF DFF
add mapped point A[19]/q A_reg[19]/QN  -type DFF DFF
add mapped point A[20]/q A_reg[20]/Q  -type DFF DFF
add mapped point A[20]/q A_reg[20]/QN  -type DFF DFF
add mapped point A[21]/q A_reg[21]/Q  -type DFF DFF
add mapped point A[21]/q A_reg[21]/QN  -type DFF DFF
add mapped point A[22]/q A_reg[22]/Q  -type DFF DFF
add mapped point A[22]/q A_reg[22]/QN  -type DFF DFF
add mapped point A[23]/q A_reg[23]/Q  -type DFF DFF
add mapped point A[23]/q A_reg[23]/QN  -type DFF DFF
add mapped point A[24]/q A_reg[24]/Q  -type DFF DFF
add mapped point A[24]/q A_reg[24]/QN  -type DFF DFF
add mapped point A[25]/q A_reg[25]/Q  -type DFF DFF
add mapped point A[25]/q A_reg[25]/QN  -type DFF DFF
add mapped point A[26]/q A_reg[26]/Q  -type DFF DFF
add mapped point A[26]/q A_reg[26]/QN  -type DFF DFF
add mapped point A[27]/q A_reg[27]/Q  -type DFF DFF
add mapped point A[27]/q A_reg[27]/QN  -type DFF DFF
add mapped point A[28]/q A_reg[28]/Q  -type DFF DFF
add mapped point A[28]/q A_reg[28]/QN  -type DFF DFF
add mapped point A[29]/q A_reg[29]/Q  -type DFF DFF
add mapped point A[29]/q A_reg[29]/QN  -type DFF DFF
add mapped point A[30]/q A_reg[30]/Q  -type DFF DFF
add mapped point A[30]/q A_reg[30]/QN  -type DFF DFF
add mapped point B[0]/q B_reg[0]/Q  -type DFF DFF
add mapped point B[0]/q B_reg[0]/QN  -type DFF DFF
add mapped point B[1]/q B_reg[1]/Q  -type DFF DFF
add mapped point B[1]/q B_reg[1]/QN  -type DFF DFF
add mapped point B[3]/q B_reg[3]/Q  -type DFF DFF
add mapped point B[3]/q B_reg[3]/QN  -type DFF DFF
add mapped point B[4]/q B_reg[4]/Q  -type DFF DFF
add mapped point B[4]/q B_reg[4]/QN  -type DFF DFF
add mapped point B[5]/q B_reg[5]/Q  -type DFF DFF
add mapped point B[5]/q B_reg[5]/QN  -type DFF DFF
add mapped point B[6]/q B_reg[6]/Q  -type DFF DFF
add mapped point B[6]/q B_reg[6]/QN  -type DFF DFF
add mapped point B[11]/q B_reg[11]/Q  -type DFF DFF
add mapped point B[11]/q B_reg[11]/QN  -type DFF DFF
add mapped point B[15]/q B_reg[15]/Q  -type DFF DFF
add mapped point B[15]/q B_reg[15]/QN  -type DFF DFF
add mapped point B[17]/q B_reg[17]/Q  -type DFF DFF
add mapped point B[17]/q B_reg[17]/QN  -type DFF DFF
add mapped point B[18]/q B_reg[18]/Q  -type DFF DFF
add mapped point B[18]/q B_reg[18]/QN  -type DFF DFF
add mapped point B[19]/q B_reg[19]/Q  -type DFF DFF
add mapped point B[19]/q B_reg[19]/QN  -type DFF DFF
add mapped point B[20]/q B_reg[20]/Q  -type DFF DFF
add mapped point B[20]/q B_reg[20]/QN  -type DFF DFF
add mapped point B[21]/q B_reg[21]/Q  -type DFF DFF
add mapped point B[21]/q B_reg[21]/QN  -type DFF DFF
add mapped point B[22]/q B_reg[22]/Q  -type DFF DFF
add mapped point B[22]/q B_reg[22]/QN  -type DFF DFF
add mapped point B[23]/q B_reg[23]/Q  -type DFF DFF
add mapped point B[23]/q B_reg[23]/QN  -type DFF DFF
add mapped point B[24]/q B_reg[24]/Q  -type DFF DFF
add mapped point B[24]/q B_reg[24]/QN  -type DFF DFF
add mapped point B[25]/q B_reg[25]/Q  -type DFF DFF
add mapped point B[25]/q B_reg[25]/QN  -type DFF DFF
add mapped point B[26]/q B_reg[26]/Q  -type DFF DFF
add mapped point B[26]/q B_reg[26]/QN  -type DFF DFF
add mapped point B[27]/q B_reg[27]/Q  -type DFF DFF
add mapped point B[27]/q B_reg[27]/QN  -type DFF DFF
add mapped point B[28]/q B_reg[28]/Q  -type DFF DFF
add mapped point B[28]/q B_reg[28]/QN  -type DFF DFF
add mapped point B[29]/q B_reg[29]/Q  -type DFF DFF
add mapped point B[29]/q B_reg[29]/QN  -type DFF DFF
add mapped point B[30]/q B_reg[30]/Q  -type DFF DFF
add mapped point B[30]/q B_reg[30]/QN  -type DFF DFF
add mapped point out[0]/q out_reg[0]/Q  -type DFF DFF
add mapped point out[1]/q out_reg[1]/Q  -type DFF DFF
add mapped point out[2]/q out_reg[2]/Q  -type DFF DFF
add mapped point out[3]/q out_reg[3]/Q  -type DFF DFF
add mapped point out[4]/q out_reg[4]/Q  -type DFF DFF
add mapped point out[5]/q out_reg[5]/Q  -type DFF DFF
add mapped point out[6]/q out_reg[6]/Q  -type DFF DFF
add mapped point out[7]/q out_reg[7]/Q  -type DFF DFF
add mapped point out[8]/q out_reg[8]/Q  -type DFF DFF
add mapped point out[9]/q out_reg[9]/Q  -type DFF DFF
add mapped point out[10]/q out_reg[10]/Q  -type DFF DFF
add mapped point out[11]/q out_reg[11]/Q  -type DFF DFF
add mapped point out[12]/q out_reg[12]/Q  -type DFF DFF
add mapped point out[13]/q out_reg[13]/Q  -type DFF DFF
add mapped point out[14]/q out_reg[14]/Q  -type DFF DFF
add mapped point out[15]/q out_reg[15]/Q  -type DFF DFF
add mapped point out[16]/q out_reg[16]/Q  -type DFF DFF
add mapped point out[17]/q out_reg[17]/Q  -type DFF DFF
add mapped point out[18]/q out_reg[18]/Q  -type DFF DFF
add mapped point out[19]/q out_reg[19]/Q  -type DFF DFF
add mapped point out[20]/q out_reg[20]/Q  -type DFF DFF
add mapped point out[21]/q out_reg[21]/Q  -type DFF DFF
add mapped point out[22]/q out_reg[22]/Q  -type DFF DFF
add mapped point out[23]/q out_reg[23]/Q  -type DFF DFF
add mapped point out[24]/q out_reg[24]/Q  -type DFF DFF
add mapped point out[25]/q out_reg[25]/Q  -type DFF DFF
add mapped point out[26]/q out_reg[26]/Q  -type DFF DFF
add mapped point out[27]/q out_reg[27]/Q  -type DFF DFF
add mapped point out[28]/q out_reg[28]/Q  -type DFF DFF
add mapped point out[29]/q out_reg[29]/Q  -type DFF DFF
add mapped point out[30]/q out_reg[30]/Q  -type DFF DFF
add mapped point out[31]/q out_reg[31]/Q  -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
